### ISSUE TITLE
README "Deploy to IBM Cloud" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vuejs-pouchdb#14]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, change the following in the "Deploy to IBM Cloud" section of the README:

- [x] Change the "Deploy to IBM Cloud" button source URL.
- [x] Change the "Deploy to IBM Cloud" button link URL.
- [x] Update the app name.
- [x] Update the prefix name.
- [x] Document the service(s) created by the deployment.
- [x] Test the "Deploy to IBM Cloud" button to ensure it works as expected.

**Comment by ptitzler** [comment]
Nothing to do. Deployment works as expected and is tracked properly.
