### ISSUE TITLE
README "Tutorial" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vuejs-pouchdb#19]
Add a tutorial section to the README, if applicable, which says:

>Refer to the [tutorial](https://github.com/ibm-watson-data-lab/shopping-list-vuejs-pouchdb/blob/master/tutorial) for step-by-step instructions on how to build your own Offline First shopping list Progressive Web App with React and PouchDB.

**Comment by terichadbourne** [comment]
@bradley-holt I reviewed this and confirmed it is correct as is. No PR needed.
