### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vuejs-pouchdb#22]
- [x] Ensure that a `LICENSE` file has been added that licenses this code under the Apache License 2.0.
- [x] Ensure that a "License" section is included in the README, using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference.

**Comment by ptitzler** [comment]
Delivered by #31
