### ISSUE TITLE
Add "Key concepts" Section

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vuejs-pouchdb#37]
Using the [README template](https://github.com/ibm-watson-data-lab/shopping-list/blob/master/templates/README.md) for reference, add a "Key concepts" section within the introductory section of the README. Ensure that any necessary modifications for this implementation have been applied.

**Comment by vabarbosa** [comment]
added with commit (https://github.com/ibm-watson-data-lab/shopping-list-vuejs-pouchdb/commit/35a77c21b5a4f4f8ec997594d1c23991787dd093#diff-04c6e90faac2675aa89e2176d2eec7d8) for issue #13

**Comment by bradley-holt** [comment]
LGTM.
