### ISSUE TITLE
About This App

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vuejs-pouchdb#52]
Ensure that an "About" (or similarly-titled) tab/page is added to the live demo version of the deployed app. Here is the boilerplate content that you can use for this tab/page:

>[Shopping List is a series of Offline First demo apps, each built using a different stack.](https://github.com/ibm-watson-data-lab/shopping-list) These demo apps cover Progressive Web Apps, hybrid mobile apps, native mobile apps, and desktop apps. This particular demo app is a **Progressive Web App** built using **Vue.js and PouchDB**. [Get the source code.](https://github.com/ibm-watson-data-lab/shopping-list-vuejs-pouchdb)

**Comment by ptitzler** [comment]
Refreshed gh-pages with the new content: https://ibm-watson-data-lab.github.io/shopping-list-vuejs-pouchdb/
