### ISSUE TITLE
Unit Testing and Continuous Integration

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-vuejs-pouchdb#9]
- [x] Set up unit testing
- [x] Set up Travis CI integration

**Comment by glynnbird** [comment]
Part of https://github.com/ibm-watson-data-lab/shopping-list-vuejs-pouchdb/pull/28

**Comment by bradley-holt** [comment]
Successfully tested on the `issue10` branch.

**Comment by bradley-holt** [comment]
LGTM.
